trigger:
  - main

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'ba-servers/BarkAvenueApi/BarkAvenueApi/BarkAvenueApi.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
  - stage: Build
    jobs:
      - job: Build
        displayName: 'Build job'
        steps:
          - checkout: self

          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '8.x'
              installationPath: $(Agent.ToolsDirectory)/dotnet

          - task: NuGetToolInstaller@1

          - task: NuGetCommand@2
            inputs:
              restoreSolution: '$(solution)'
              feedsToUse: 'config'
              nugetConfigPath: '$(Build.SourcesDirectory)/ba-servers/BarkAvenueApi/BarkAvenueApi/nuget.config'

          - task: DotNetCoreCLI@2
            inputs:
              command: 'build'
              projects: '$(solution)'
              arguments: '--configuration $(buildConfiguration)'

          - task: DotNetCoreCLI@2
            inputs:
              command: 'test'
              projects: '$(solution)'
              arguments: '--configuration $(buildConfiguration)'

          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: '$(Build.SourcesDirectory)/ba-servers/BarkAvenueApi/BarkAvenueApi/bin/Release/net8.0/publish'
              artifactName: 'drop'

  - stage: DeployStaging
    jobs:
      - deployment: DeployStaging
        displayName: 'Deploy Staging job'
        environment: 'Staging'
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: drop

                - task: AzureRmWebAppDeployment@4
                  inputs:
                    ConnectionType: 'AzureRM'
                    azureSubscription: 'Azuresubscription1'
                    appType: 'webApp'
                    WebAppName: 'test08765'
                    package: '$(Pipeline.Workspace)/drop/WebApp.zip'

  - stage: DeployProduction
    jobs:
      - deployment: DeployProduction
        displayName: 'Deploy Production job'
        environment: 'Production'
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: drop

                - task: AzureRmWebAppDeployment@4
                  inputs:
                    ConnectionType: 'AzureRM'
                    azureSubscription: 'Azuresubscription1'
                    appType: 'webApp'
                    WebAppName: 'test08765'
                    package: '$(Pipeline.Workspace)/drop/WebApp.zip'
