# ASP.NET Core (.NET Framework)
# Збирайте та тестуйте проекти ASP.NET Core, спрямовані на повний .NET Framework.
# Додайте кроки, які публікують символи, зберігають артефакти збирання та інше:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# Конфігурація збирання та розгортання Azure App Service
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'test'  # Оновіть це значення на своє підключення до Azure
    appType: 'webApp'
    WebAppName: 'test08765'  # Замініть 'test08765' на назву вашого веб-додатку Azure
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'  # При потребі відредагуйте цей шлях
