trigger:
  - main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'  # Update the path to your solution file

  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
  - stage: Build
    jobs:
      - job: Build
        displayName: 'Build job'
        steps:
          - task: NuGetToolInstaller@1

          - task: NuGetCommand@2
            inputs:
              restoreSolution: '$(solution)'

          - task: DotNetCoreCLI@2  # Use DotNetCoreCLI task for .NET Core projects
            inputs:
              command: 'build'
              projects: '$(solution)'
              arguments: '--configuration $(buildConfiguration)'

          - task: VSTest@2
            inputs:
              platform: '$(buildPlatform)'
              configuration: '$(buildConfiguration)'

          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: '$(Build.ArtifactStagingDirectory)'
              artifactName: 'drop'

  - stage: DeployStaging
    jobs:
      - deployment: DeployStaging
        displayName: 'Deploy Staging job'
        environment: 'Staging'
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: drop

                - task: AzureRmWebAppDeployment@4
                  inputs:
                    ConnectionType: 'AzureRM'
                    azureSubscription: 'Azuresubscription1'  
                    appType: 'webApp'
                    WebAppName: 'test08765'
                    package: '$(Pipeline.Workspace)/drop/WebApp.zip'

  - stage: DeployProduction
    jobs:
      - deployment: DeployProduction
        displayName: 'Deploy Production job'
        environment: 'Production'
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: drop

                - task: AzureRmWebAppDeployment@4
                  inputs:
                    ConnectionType: 'AzureRM'
                    azureSubscription: 'Azuresubscription1' 
                    appType: 'webApp'
                    WebAppName: 'test08765'
                    package: '$(Pipeline.Workspace)/drop/WebApp.zip'